name: Backend_services

const_context: &context ../../
const_dockerfile: &Dockerfile docker/dev/Dockerfile
const_image: &image ${DOCKERHUB_USERNAME}/${GITHUB_REPO_NAME}

template_extends_base: &extends_backend_base
  extends:
    service: backend_base

template_extends_generic: &extends_backend_generic
  extends:
    service: backend_generic

template_extends_bot_generic: &extends_bot_generic
  extends:
    service: bot_generic

template_extends_fastapi_generic: &extends_fastapi_generic
  extends:
    service: fastapi_generic

template_build: &build_app
  context: *context
  dockerfile: *Dockerfile
  target: app

template_develop: &develop
  watch:
    - path: ../../src
      action: rebuild
    - path: ../../config
      action: rebuild
    - path: ../../requirements
      action: rebuild

services:

  backend_base:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../.env


  backend_test:
    <<: *extends_backend_base
    container_name: test_backend
    build:
      context: *context
      dockerfile: *Dockerfile
      target: test
    command: bash -c "pytest"


  backend_generic:
    <<: *extends_backend_base
    restart: always
    networks:
      - backend


  bot_generic:
    <<: *extends_backend_generic
    container_name: bot
    command: bash -c "alembic upgrade head && python -m src.bot"  # /main.py"

  bot_dev:
    <<: *extends_bot_generic
    build: *build_app
    develop: *develop

  bot_prod:
    <<: *extends_bot_generic
    image: *image


  fastapi_generic:
    <<: *extends_backend_generic
    container_name: fastapi
    command:
      bash -c "alembic upgrade head && uvicorn src.fastapi.main:app --host=0.0.0.0 --port=8000"
    ports:
      - "${APP_PORT:-8000}:8000"

  fastapi_dev:
    <<: *extends_fastapi_generic
    build: *build_app
    develop: *develop
    # volumes:  # bind mount for online coding
    #  - ../../src:/app/src
    # https://docs.docker.com/compose/how-tos/file-watch/

  fastapi_prod:
    <<: *extends_fastapi_generic
    image: *image
    # "${DOCKERHUB_USERNAME}/${GITHUB_REPO_NAME}"
    # networks:
    #   - frontend
    #   - backend
    # expose:
    #  - ${APP_DEV_PORT:-8000}


 # backend_migration:
  #   container_name: migration
  #   <<: *extends_backend_base
  #   build:
  #     context: *context
  #     dockerfile: *Dockerfile
  #     target: migration
  #   command: bash -c "alembic revision --autogenerate"
  #   volumes:  # bind mount for online coding
  #     - ../../alembic:/app/alembic
  #   networks:
  #     - admin
