name: user_account + _prod

services:

  fastapi:
    extends:
      file: ../base/backend.yaml
      service: fastapi_prod

  adminer:
    extends:
      file: ../base/db.yaml
      service: adminer

  db:
    extends:
      file: ../base/db.yaml
      service: db

  redis:
    image: redis:latest
    container_name: cache
    networks:
      - backend


networks:
  admin:
    name: admin
  backend:
    name: backend

volumes:
  db_vol:
