name: Tests Ruff and pytest


on:
  workflow_call:
#    secrets:
#      codecov_token:
#        required: true


jobs:
  tests:
    name: Tests Ruff and pytest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: github_actions
          POSTGRES_PASSWORD: github_actions
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Ruff check
        uses: chartboost/ruff-action@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip && pip install ".[test]"

      - name: Run Tests
        env:
          TEST_DB_HOST: 0.0.0.0
          REDIS_HOST: 0.0.0.0
        run: |
          pytest -sv -W ignore


#          --cov --cov-report=xml
#      - name: Upload coverage reports to Codecov with GitHub Action
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          verbose: true
# ${{ secrets.GHH }}
# ${{ secrets.GHA }}
