name: Push Docker image to Docker Hub


on:
  workflow_call:


jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/dev/Dockerfile
          target: app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

        # - name: Build and push Docker image
        #   uses: docker/build-push-action@v6
        #   with:
        #     push: ${{ github.event_name != 'pull_request' }}
        #     tags: ${{ steps.meta.outputs.tags }}
        #     annotations: ${{ steps.meta.outputs.annotations }}
        #     provenance: true
        #     sbom: true
