name: Setup host environment


on:
  workflow_call:


jobs:
  server_environment:
    name: Setup host environment
    runs-on: ubuntu-latest
    steps:
      - name: Create project directory and .env-file
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            sudo mkdir -p ${{ github.event.repository.name }} -m 777
            sudo cat > ${{ github.event.repository.name }}/.env << _EOF_

              BOT_TOKEN=${{ secrets.BOT_TOKEN }}
              APP_PORT=${{ vars.APP_PORT }}
              APP_TITLE=${{ vars.APP_TITLE }}
              APP_DESCRIPTION=${{ vars.APP_DESCRIPTION }}
              SECRET_KEY=${{ secrets.SECRET_KEY }}

              DB_ADMIN_PORT=${{ vars.DB_ADMIN_PORT }}
              DB_TAG=15.1-alpine
              DB_DEFAULT=postgres
              DB_USER=postgres
              DB_PASSWORD=postgres
              DB_HOST=postgres
              DB_PORT=5432
              DB_NAME=postgres

              # Below are examples for secrets and vars
                # DB_USER=${{ secrets.DB_USER }}
                # DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                # DB_HOST=${{ vars.DB_HOST }}
                # DB_PORT=${{ vars.DB_PORT }}
                # DB_NAME=${{ vars.DB_NAME }}

              # INTERVAL=10s
              # TIMEOUT=10s
              # RETRIES=3
              # START_PERIOD=10s

              DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
              GITHUB_REPO_NAME=${{ github.event.repository.name }}:latest

            _EOF_

      - uses: actions/checkout@v4
      - name: copy infra files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source: "docker/base/, docker/prod/"
          target: ${{ github.event.repository.name }}
          overwrite: true
          # strip_components: 1
